#!/bin/bash

#
# script to build Aaron Christophel's  ATCwatch
# from: https://github.com/atc1441/ATCwatch.git
#

date

if [ $# != 1 ]
then 
	echo "usage: setup newdir"
fi

# Fail if file or direcotry exists with given name
if [[ -e $1 ]]
then
	echo $1 must not exist a new directory will be wade with that name
	exit 1
fi

# 
#create build directory
#

Workdir=$1
mkdir $Workdir
cd $Workdir 

# setup needed librarys that we have to extract
mkdir -p Arduino/libraries/

#make a setenv file to help users later
echo export  HOME=`pwd` > setenv
echo export  PATH=$PATH:`pwd`/.local/bin/ >> setenv
chmod +x setenv
#make a build file to help users later
echo export  HOME=`pwd` > build
echo export  PATH=$PATH:`pwd`/.local/bin/ >> build
echo cd `pwd` >> build
echo './arduino-cli compile --clean -e -b nRF52D6Fitness:nRF5:dsd6Watch ATCwatch/ATCwatch/' >> build
chmod +x build

#change HOME to be here to keep real HOME clean all files in this dir
export HOME=`pwd`

# install local standalone copy of nrfutil
pip3 install wheel --user
pip3 install adafruit-nrfutil --user
# add to PATH
export PATH=$PATH:$HOME/.local/bin

####
#### get arduino-cli
####
#donwload
wget --no-check-certificate  https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
# extract
tar xvf arduino-cli_latest_Linux_64bit.tar.gz  arduino-cli
rm  arduino-cli_latest_Linux_64bit.tar.gz 


# get HRS33000 library from git
git clone https://github.com/atc1441/HRS3300-Arduino-Library.git Arduino/libraries/HRS3300-Arduino-Library 

# git clone https://github.com/lvgl/lv_arduino.git
git clone https://github.com/elazarrosenthal/lv_arduino.git -b atcwatch Arduino/libraries/lv_arduino 


# get ATC WATCH archive
git clone https://github.com/atc1441/ATCwatch.git

# set up aruino-cli config 
./arduino-cli config init

# Real one but has a bas size in json
# BOARDURL=https://atc1441.github.io/D6Library/package_nRF5_boards_index.json
# elazarrosenthal copy with fixed size use above once it is fixed
BOARDURL=https://raw.githubusercontent.com/elazarrosenthal/AtcWatchBuilder/c69789c244c92b336c90788d18b796e6d1f0e112/package_nRF5_boards_index.json

# Install Board For the watch
./arduino-cli config add board_manager.additional_urls $BOARDURL
./arduino-cli core install nRF52D6Fitness:nRF5 
./arduino-cli core update-index


###
### edit files to allow for .a from HRS code
###
# make backup of file to edit
cp .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.orig
cp .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.new

# add line 
echo "compiler.libraries.ldflags=" >> .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.new
# append to line 
sed 's/combine.pattern.*/& \{compiler.libraries.ldflags\}/'  < .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.new > .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.new2

#  overwrite file with changes
cp .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt.new2 .arduino15/packages/nRF52D6Fitness/hardware/nRF5/0.7.5/platform.txt 


####
#### buildit 
####
./arduino-cli  board attach -b nRF52D6Fitness:nRF5:dsd6Watch  ATCwatch/ATCwatch/
./arduino-cli compile --clean -e -b nRF52D6Fitness:nRF5:dsd6Watch ATCwatch/ATCwatch/
date
